name: "sonar_cloud_scan_github_actions"
on:
  workflow_dispatch:

jobs:
  DemoSonarCloudSCan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.GIT_PAT }}
        with:
          args: >
              -Dsonar.organization=github-myserver-co-in
              -Dsonar.projectKey=github-myserver-co-in_SonarCloudCodeAnalyisis
              -Dsonar.python.coverage.reportPaths=coverage.xml
